variable "vpc_cidr" {}
variable "env" {}
variable "project_name" {}
variable "public_subnets" {}
variable "web_subnets" {}
variable "app_subnets" {}
variable "db_subnets" {}
variable "azs" {}
variable "account_no" {}
variable "default_vpc_id" {}
variable "default_vpc_cidr" {}
variable "default_route_table_id" {}
variable "instance_class" {}
variable "docdb_instance_count" {}
variable "docdb_instance_class" {}
variable "ec_node_type" {}
variable "ec_node_count" {}
variable "rabbitmq_instance_type" {}
variable "bastion_node_cidr" {}